<?php

namespace Enna\Framework\Console\Command;

use Enna\Framework\Console\Command;
use Enna\Framework\Console\Input;
use Enna\Framework\Console\Output;

class ServiceDiscover extends Command
{
    protected function configure()
    {
        $this->setName('service:discover')
            ->setDescription('Discover Services');
    }

    protected function execute(Input $input, Output $output)
    {

        if (is_file($path = $this->app->getRootPath() . 'vendor/composer/installed.json')) {
            $packages = json_decode(@file_get_contents($path), true);

            if (isset($packages['packages'])) {
                $packages = $packages['packages'];
            }
            
            $services = [];
            foreach ($packages as $package) {
                if (!empty($package['extra']['enna']['services'])) {
                    $services = array_merge($services, (array)$package['extra']['enna']['services']);
                }
            }

            $header = '// This file is automatically generated at:' . date('Y-m-d H:i:s') . PHP_EOL . 'declare (strict_type = 1);' . PHP_EOL;

            $content = '<?php ' . PHP_EOL . $header . 'return ' . var_export($services, true) . ';';

            file_put_contents($this->app->getRootPath() . 'vendor/services.php', $content);

            $output->writeln('<info>Succeed!</info>');
        }
    }
}