<?php
declare(strict_types=1);

namespace Enna\Framework;

class Session extends Manager
{
    protected $namespace = '';

    protected function createDriver(string $name)
    {
        return parent::createDriver($name); // TODO: Change the autogenerated stub
    }
}